import Head from "next/head";
import ImageGallary from "~/components/Image/Gallery";
import TopBar from "~/components/Core/TopBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Image Gallery App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <TopBar />
        <ImageGallary />
      </main>
    </>
  );
}
